

#################################### global configure #######################################

username: minixbeta
baseurl: /StrayBirds
markdown: redcarpet
safe: false
highlighter: pygments
title: 飞鸟集
description: 人生到处知何似，应似飞鸿踏雪泥
theme: kunka
disqusname: minixalpha

